# Generated by Django 5.0.1 on 2024-01-04 05:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='affairs',
            fields=[
                ('affairs_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headquarter', models.CharField(max_length=30, null=True)),
                ('center', models.CharField(max_length=30, null=True)),
                ('team', models.CharField(max_length=30, null=True)),
                ('affairs', models.CharField(max_length=30, null=True)),
                ('cust_no', models.CharField(max_length=30, null=True)),
                ('contract', models.CharField(max_length=30, null=True)),
                ('powertocost', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='affairspower',
            fields=[
                ('affairspower_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('affairs', models.CharField(max_length=30, null=True)),
                ('power', models.CharField(max_length=30, null=True)),
                ('time', models.CharField(max_length=30, null=True)),
                ('affairs_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kepco.affairs')),
            ],
        ),
    ]
